default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_post_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: blog_post_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: blog_post_production
  username: blog_post
  password: <%= ENV['BLOG_POST_DATABASE_PASSWORD'] %>
